### ISSUE TITLE
clean 之后的离线 vc 展示和出示都不正确了

### ISSUE THREAD

**Issue by wangshijun** [blocklet/clean-wallet#5]
必须找回 passport 才能正确 work。

复现方法：

- 启动本地 server
- 用 web-wallet 领取 passport
- 导出备份，到远程的 clean-wallet 瘦身
- 导入瘦身后的钱包
- 重新登陆 server，passport 图破了，并且提供时出错

![Screen Shot 2022-03-04 at 18 09 24](https://user-images.githubusercontent.com/719985/156744030-7864795b-d3eb-431a-af88-815af7e405ab.png)

![Screen Shot 2022-03-04 at 18 09 30](https://user-images.githubusercontent.com/719985/156744021-db9c3c91-d4a1-421d-8deb-5a14d9b4e1be.png)

**Comment by leermao** [comment]
fixed
